presubmits:
  - name: presubmit-kbp-test
    decorate: true
    always_run: true
    spec:
      containers:
        - image: node:16-alpine3.16
          command:
            - '/bin/sh'
            - '-c'
            - |
              set -euo pipefail
              yarn install --frozen-lockfile
              yarn test:all

  - name: presubmit-kbp-lint
    decorate: true
    always_run: true
    spec:
      containers:
        - image: node:16-alpine3.16
          command:
            - '/bin/sh'
            - '-c'
            - |
              set -euo pipefail
              yarn install --frozen-lockfile
              yarn lint:all
              yarn tsc:full
              yarn prettier:check
  - name: presubmit-kbp-license-header-check
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        - "-c"
        - |
          /usr/local/bin/checklicense.sh > ${ARTIFACTS}/license_headers_results.txt
  - name: presubmit-kbp-scancode-toolkit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/scancode-toolkit:v31.2.5
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          /scancode-toolkit/scancode --ignore "whitelist.json" -clpeui -n 2 --html ${ARTIFACTS}/scancode_report.html . --tallies-with-details
        resources:
          requests:
            cpu: 2
            memory: 1Gi
  - name: presubmit-kbp-fossology
    decorate: true
    always_run: true
    spec:
      containers:
      - image: fossology/fossology:scanner
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /bin/fossologyscanner repo nomos ojo copyright keyword
          cp -R results ${ARTIFACTS}/    
