presubmits:
  - name: presubmit-kbp-test
    decorate: true
    always_run: true
    spec:
      containers:
        - image: node:16-alpine3.16
          command:
            - '/bin/sh'
            - '-c'
            - |
              set -euo pipefail
              apk update
              apk add python3 make g++
              yarn install --frozen-lockfile
              yarn test:all

  - name: presubmit-kbp-lint
    decorate: true
    always_run: true
    spec:
      containers:
        - image: node:16-alpine3.16
          command:
            - '/bin/sh'
            - '-c'
            - |
              set -euo pipefail
              apk update
              apk add python3 make g++
              yarn install --frozen-lockfile
              yarn lint:all
              yarn tsc:full
              yarn prettier:check

  - name: presubmit-kbp-license-header-check
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        - "-c"
        - |
          /usr/local/bin/checklicense.sh > ${ARTIFACTS}/license_headers_results.txt

  - name: presubmit-kbp-scancode-toolkit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/scancode-toolkit:v31.2.5
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          /scancode-toolkit/scancode --ignore "whitelist.json" -clpeui -n 2 --html ${ARTIFACTS}/scancode_report.html . --tallies-with-details
        resources:
          requests:
            cpu: 2
            memory: 1Gi

  - name: presubmit-kbp-fossology
    decorate: true
    always_run: true
    spec:
      containers:
      - image: fossology/fossology:scanner
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /bin/fossologyscanner --report SPDX_JSON repo nomos ojo copyright keyword
          cp -R results ${ARTIFACTS}/

  - name: build-push-pre-image-kbp
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Presubmit Image to Hub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 0
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=${PWD} \
            --dockerfile=Dockerfile --destination=nephio/pre-kpt-backstage-plugins:${BUILD_ID}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 2
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
